//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.data;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class InfoFile_
    extends SharedPreferencesHelper
{


    public InfoFile_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public InfoFile_.InfoFileEditor_ edit() {
        return new InfoFile_.InfoFileEditor_(getSharedPreferences());
    }

    public StringPrefField ZTYWkaishishijian() {
        return stringField("ZTYWkaishishijian", "");
    }

    public StringPrefField ZTYWyuanyin() {
        return stringField("ZTYWyuanyin", "");
    }

    public StringPrefField banjieriqi() {
        return stringField("banjieriqi", "");
    }

    public StringPrefField baselist_yewuliushuihao() {
        return stringField("baselist_yewuliushuihao", "");
    }

    public StringPrefField bdlr_ywlsh() {
        return stringField("bdlr_ywlsh", "");
    }

    public StringPrefField bizArchivesId() {
        return stringField("bizArchivesId", "");
    }

    public StringPrefField bz_msg() {
        return stringField("bz_msg", "");
    }

    public StringPrefField bz_slczy() {
        return stringField("bz_slczy", "");
    }

    public StringPrefField bz_sqr_phone() {
        return stringField("bz_sqr_phone", "");
    }

    public StringPrefField bz_yy() {
        return stringField("bz_yy", "");
    }

    public StringPrefField dfflb_bjzt() {
        return stringField("dfflb_bjzt", "");
    }

    public StringPrefField dxtz_beizhu() {
        return stringField("dxtz_beizhu", "");
    }

    public StringPrefField dxtz_shibaiyuanyin() {
        return stringField("dxtz_shibaiyuanyin", "");
    }

    public StringPrefField infoCookie() {
        return stringField("infoCookie", "");
    }

    public StringPrefField infoPassword() {
        return stringField("infoPassword", "");
    }

    public StringPrefField infoUserId() {
        return stringField("infoUserId", "");
    }

    public StringPrefField infoUsername() {
        return stringField("infoUsername", "");
    }

    public BooleanPrefField isAutoLogin() {
        return booleanField("isAutoLogin", false);
    }

    public StringPrefField jgff_yewuliushuihao() {
        return stringField("jgff_yewuliushuihao", "");
    }

    public StringPrefField numOfDffzs() {
        return stringField("numOfDffzs", "");
    }

    public StringPrefField numOfDqwbjzs() {
        return stringField("numOfDqwbjzs", "");
    }

    public StringPrefField numOfDspzs() {
        return stringField("numOfDspzs", "");
    }

    public StringPrefField numOfYslzs() {
        return stringField("numOfYslzs", "");
    }

    public StringPrefField postinfoid() {
        return stringField("postinfoid", "");
    }

    public StringPrefField postinfoname() {
        return stringField("postinfoname", "");
    }

    public StringPrefField postinfotype() {
        return stringField("postinfotype", "");
    }

    public StringPrefField serviceSubjectId() {
        return stringField("serviceSubjectId", "");
    }

    public StringPrefField serviceSubjectName() {
        return stringField("serviceSubjectName", "");
    }

    public StringPrefField serviceTargetPhone() {
        return stringField("serviceTargetPhone", "");
    }

    public StringPrefField shengqingrenCardId() {
        return stringField("shengqingrenCardId", "");
    }

    public StringPrefField shengqingrenname() {
        return stringField("shengqingrenname", "");
    }

    public StringPrefField shengqingriqi() {
        return stringField("shengqingriqi", "");
    }

    public StringPrefField wssq_wsyslh() {
        return stringField("wssq_wsyslh", "");
    }

    public StringPrefField yslyw_shengqingrenCardId() {
        return stringField("yslyw_shengqingrenCardId", "");
    }

    public final static class InfoFileEditor_
        extends EditorHelper<InfoFile_.InfoFileEditor_>
    {


        InfoFileEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> ZTYWkaishishijian() {
            return stringField("ZTYWkaishishijian");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> ZTYWyuanyin() {
            return stringField("ZTYWyuanyin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> banjieriqi() {
            return stringField("banjieriqi");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> baselist_yewuliushuihao() {
            return stringField("baselist_yewuliushuihao");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bdlr_ywlsh() {
            return stringField("bdlr_ywlsh");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bizArchivesId() {
            return stringField("bizArchivesId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_msg() {
            return stringField("bz_msg");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_slczy() {
            return stringField("bz_slczy");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_sqr_phone() {
            return stringField("bz_sqr_phone");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_yy() {
            return stringField("bz_yy");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> dfflb_bjzt() {
            return stringField("dfflb_bjzt");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> dxtz_beizhu() {
            return stringField("dxtz_beizhu");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> dxtz_shibaiyuanyin() {
            return stringField("dxtz_shibaiyuanyin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoCookie() {
            return stringField("infoCookie");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoPassword() {
            return stringField("infoPassword");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUserId() {
            return stringField("infoUserId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUsername() {
            return stringField("infoUsername");
        }

        public BooleanPrefEditorField<InfoFile_.InfoFileEditor_> isAutoLogin() {
            return booleanField("isAutoLogin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> jgff_yewuliushuihao() {
            return stringField("jgff_yewuliushuihao");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> numOfDffzs() {
            return stringField("numOfDffzs");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> numOfDqwbjzs() {
            return stringField("numOfDqwbjzs");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> numOfDspzs() {
            return stringField("numOfDspzs");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> numOfYslzs() {
            return stringField("numOfYslzs");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> postinfoid() {
            return stringField("postinfoid");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> postinfoname() {
            return stringField("postinfoname");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> postinfotype() {
            return stringField("postinfotype");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> serviceSubjectId() {
            return stringField("serviceSubjectId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> serviceSubjectName() {
            return stringField("serviceSubjectName");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> serviceTargetPhone() {
            return stringField("serviceTargetPhone");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shengqingrenCardId() {
            return stringField("shengqingrenCardId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shengqingrenname() {
            return stringField("shengqingrenname");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shengqingriqi() {
            return stringField("shengqingriqi");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> wssq_wsyslh() {
            return stringField("wssq_wsyslh");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> yslyw_shengqingrenCardId() {
            return stringField("yslyw_shengqingrenCardId");
        }

    }

}
