//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.ZWPT.activity.R.id;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;
import com.ZWPT.data.InfoFile_;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class Base_ListActivity_
    extends Base_ListActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.layout_base_list);
    }

    private void init_(Bundle savedInstanceState) {
        infoFile_ = new InfoFile_(this);
        dataHelper = DataHelper_.getInstance_(this);
    }

    private void afterSetContentView_() {
        ll_search = ((LinearLayout) findViewById(id.ll_search));
        rl_title = ((RelativeLayout) findViewById(id.rl_title));
        tv_search_5 = ((TextView) findViewById(id.tv_search_5));
        title_search = ((ImageButton) findViewById(id.title_search));
        search_rll_banjianriqi = ((LinearLayout) findViewById(id.search_rll_banjianriqi));
        search_rll_fenlei = ((LinearLayout) findViewById(id.search_rll_fenlei));
        edt_search_3 = ((EditText) findViewById(id.edt_search_3));
        tv_search_1 = ((TextView) findViewById(id.tv_search_1));
        search_rll_banjianriqi_to = ((LinearLayout) findViewById(id.search_rll_banjianriqi_to));
        edt_search_1 = ((EditText) findViewById(id.edt_search_1));
        lv_base = ((ListView) findViewById(id.lv_base));
        tv_search_3 = ((TextView) findViewById(id.tv_search_3));
        btn_search = ((Button) findViewById(id.btn_search));
        search_rll_shenqingriqi = ((LinearLayout) findViewById(id.search_rll_shenqingriqi));
        search_rll_all = ((LinearLayout) findViewById(id.search_rll_all));
        tv_search_2 = ((TextView) findViewById(id.tv_search_2));
        search_rll_shenqingriqi_to = ((LinearLayout) findViewById(id.search_rll_shenqingriqi_to));
        tv_search_4 = ((TextView) findViewById(id.tv_search_4));
        edt_search_4 = ((EditText) findViewById(id.edt_search_4));
        edt_search_2 = ((EditText) findViewById(id.edt_search_2));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static Base_ListActivity_.IntentBuilder_ intent(Context context) {
        return new Base_ListActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Base_ListActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Base_ListActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
