//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.ZWPT.activity.R.id;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;
import com.ZWPT.data.InfoFile_;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class Base_DetailActivity_
    extends Base_DetailActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.layout_datail_bar);
    }

    private void init_(Bundle savedInstanceState) {
        infoFile_ = new InfoFile_(this);
        dataHelper = DataHelper_.getInstance_(this);
    }

    private void afterSetContentView_() {
        rb2 = ((RadioButton) findViewById(id.rb2));
        btn_duanxintongzhi = ((Button) findViewById(id.btn_duanxintongzhi));
        rl_title = ((RelativeLayout) findViewById(id.rl_title));
        btn_chuliyewu = ((Button) findViewById(id.btn_chuliyewu));
        rb1 = ((RadioButton) findViewById(id.rb1));
        btn_tuihuiyewu = ((Button) findViewById(id.btn_tuihuiyewu));
        btn_buzhengtongzhi = ((Button) findViewById(id.btn_buzhengtongzhi));
        detail_btn_llbd = ((Button) findViewById(id.detail_btn_llbd));
        rb5 = ((RadioButton) findViewById(id.rb5));
        btn_FanHui = ((Button) findViewById(id.btn_FanHui));
        ll_detail_btn_2 = ((LinearLayout) findViewById(id.ll_detail_btn_2));
        detail_btn_buzhengshouli = ((Button) findViewById(id.detail_btn_buzhengshouli));
        frameL_title = ((FrameLayout) findViewById(id.frameL_title));
        ll_detail_btn_5 = ((LinearLayout) findViewById(id.ll_detail_btn_5));
        btn_zantingyewu = ((Button) findViewById(id.btn_zantingyewu));
        ll_detail_btn_4 = ((LinearLayout) findViewById(id.ll_detail_btn_4));
        ll_detail_btn_6 = ((LinearLayout) findViewById(id.ll_detail_btn_6));
        btn_ShouLi = ((Button) findViewById(id.btn_ShouLi));
        btn_fafangjieguo = ((Button) findViewById(id.btn_fafangjieguo));
        ll_detail_btn_1 = ((LinearLayout) findViewById(id.ll_detail_btn_1));
        ll_detail_btn_3 = ((LinearLayout) findViewById(id.ll_detail_btn_3));
        radiogroup = ((RadioGroup) findViewById(id.radiogroup));
        rb4 = ((RadioButton) findViewById(id.rb4));
        rb9 = ((RadioButton) findViewById(id.rb9));
        rb10 = ((RadioButton) findViewById(id.rb10));
        rb6 = ((RadioButton) findViewById(id.rb6));
        tv_jgjf_item_1 = ((TextView) findViewById(id.tv_jgjf_item_1));
        rb3 = ((RadioButton) findViewById(id.rb3));
        btn_BuShouLi = ((Button) findViewById(id.btn_BuShouLi));
        rb8 = ((RadioButton) findViewById(id.rb8));
        rb7 = ((RadioButton) findViewById(id.rb7));
        detail_btn_kaishi = ((Button) findViewById(id.detail_btn_kaishi));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static Base_DetailActivity_.IntentBuilder_ intent(Context context) {
        return new Base_DetailActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Base_DetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Base_DetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
