//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;
import com.ZWPT.data.InfoFile_;

public final class Detail_jbxxFragment_
    extends Detail_jbxxFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        oFile_ = new InfoFile_(getActivity());
        dataHelper = DataHelper_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tv_jgjf_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgjf_item_3));
        tv_jgjf_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgjf_item_5));
        ll_ywcl_2 = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_ywcl_2));
        tv_sjdj_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_4));
        tv_wssl_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wssl_item_6));
        tv_wssl_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wssl_item_2));
        tv_ywcl_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_6));
        btn_detail_jgjf_spcgcl = ((ImageButton) findViewById(com.ZWPT.activity.R.id.btn_detail_jgjf_spcgcl));
        tv_ywcl_2_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_2));
        tv_wssl_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wssl_item_4));
        tv_jgdj_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_4));
        tv_ywcl_2_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_4));
        tv_sjdj_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_5));
        tv_ywcl_2_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_1));
        ll_bdlr = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_bdlr));
        tv_wssl_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wssl_item_1));
        tv_ywcl_2_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_5));
        tv_wxts_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wxts_item_2));
        tv_bdlr_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_bdlr_item_4));
        tv_ywcl_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_3));
        btn_detail_shjg_spcgcl = ((ImageButton) findViewById(com.ZWPT.activity.R.id.btn_detail_shjg_spcgcl));
        tv_bdlr_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_bdlr_item_5));
        ll_jgjf = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_jgjf));
        tv_ywcl_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_5));
        tv_ywcl_item_7 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_7));
        tv_jgjf_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgjf_item_1));
        tv_jgdj_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_2));
        tv_bdlr_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_bdlr_item_2));
        tv_sjdj_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_3));
        tv_jgdj_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_6));
        ll_wssl = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_wssl));
        tv_wxts_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wxts_item_1));
        tv_sjdj_item_7 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_7));
        tv_ywcl_2_item_7 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_7));
        tv_wxts_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wxts_item_3));
        tv_ywcl_2_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_6));
        linearlayout_shjg = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.linearlayout_shjg));
        ll_sjdj = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_sjdj));
        ll_jgdj = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_jgdj));
        tv_sjdj_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_6));
        tv_jgdj_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_1));
        tv_ywcl_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_1));
        btn_detail_shjg_spcgcl2 = ((ImageButton) findViewById(com.ZWPT.activity.R.id.btn_detail_shjg_spcgcl2));
        tv_jgdj_item_7 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_7));
        tv_bdlr_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_bdlr_item_6));
        tv_wssl_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wssl_item_3));
        tv_sjdj_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_1));
        tv_jgjf_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgjf_item_2));
        tv_jgdj_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_5));
        linearlayout_shjg2 = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.linearlayout_shjg2));
        tv_jgdj_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgdj_item_3));
        tv_ywcl_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_2));
        tv_bdlr_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_bdlr_item_1));
        tv_ywcl_2_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_2_item_3));
        ll_ywcl = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_ywcl));
        tv_ywcl_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_ywcl_item_4));
        linearlayout_jgjf = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.linearlayout_jgjf));
        tv_bdlr_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_bdlr_item_3));
        ll_wxts = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_wxts));
        tv_sjdj_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_item_2));
        tv_jgjf_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_jgjf_item_4));
        tv_wssl_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_wssl_item_5));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_detail_jbxx, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static Detail_jbxxFragment_.FragmentBuilder_ builder() {
        return new Detail_jbxxFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public Detail_jbxxFragment build() {
            Detail_jbxxFragment_ fragment_ = new Detail_jbxxFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
