//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;
import com.ZWPT.data.InfoFile_;

public final class Detail_ffjlFragment_
    extends Detail_ffjlFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        infoFile_ = new InfoFile_(getActivity());
        dataHelper = DataHelper_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tv_list_item_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_2));
        tv_list_item_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_3));
        dxxq = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.dxxq));
        tv_list_item_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_4));
        tv_list_item_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_5));
        tv_list_item_dx_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_dx_2));
        tv_list_item_dx_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_dx_3));
        tv_list_item_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_1));
        tv_list_item_dx_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_dx_1));
        tv_list_item_dx_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_dx_4));
        tv_list_item_dx_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_dx_5));
        tv_list_item_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_list_item_6));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_detail_ffjl, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static Detail_ffjlFragment_.FragmentBuilder_ builder() {
        return new Detail_ffjlFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public Detail_ffjlFragment build() {
            Detail_ffjlFragment_ fragment_ = new Detail_ffjlFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
