//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;

public final class Detail_sjdjFargment_
    extends Detail_sjdjFargment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        InfoFile_ = new com.ZWPT.data.InfoFile_(getActivity());
        dataHelper = DataHelper_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        name_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.name_6));
        tv_sjdj_djxx_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_djxx_3));
        tv_sjdj_djxx_6 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_djxx_6));
        tv_sjdj_djxx_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_djxx_4));
        tv_sjdj_djxx_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_djxx_5));
        lv_detail_sjdj_tjcl = ((ListView) findViewById(com.ZWPT.activity.R.id.lv_detail_sjdj_tjcl));
        lv_detail_sjdj_tjcl_checks = ((ListView) findViewById(com.ZWPT.activity.R.id.lv_detail_sjdj_tjcl_checks));
        dzzz = ((TextView) findViewById(com.ZWPT.activity.R.id.dzzz));
        ll_6 = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_6));
        name_3 = ((TextView) findViewById(com.ZWPT.activity.R.id.name_3));
        name_5 = ((TextView) findViewById(com.ZWPT.activity.R.id.name_5));
        name_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.name_2));
        tv_sjdj_djxx_2 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_djxx_2));
        btn_check_tiaojian = ((Button) findViewById(com.ZWPT.activity.R.id.btn_check_tiaojian));
        tv_sjdj_djxx_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.tv_sjdj_djxx_1));
        name_1 = ((TextView) findViewById(com.ZWPT.activity.R.id.name_1));
        lv_detail_sjdj_bltj = ((ListView) findViewById(com.ZWPT.activity.R.id.lv_detail_sjdj_bltj));
        name_4 = ((TextView) findViewById(com.ZWPT.activity.R.id.name_4));
        sfsq = ((TextView) findViewById(com.ZWPT.activity.R.id.sfsq));
        ll_sjdj_tjcl_checkbox = ((LinearLayout) findViewById(com.ZWPT.activity.R.id.ll_sjdj_tjcl_checkbox));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_detail_sjdj, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static Detail_sjdjFargment_.FragmentBuilder_ builder() {
        return new Detail_sjdjFargment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public Detail_sjdjFargment build() {
            Detail_sjdjFargment_ fragment_ = new Detail_sjdjFargment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
