//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.ZWPT.activity.R.id;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;
import com.ZWPT.data.InfoFile_;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class Jgff_Dfflb_ff_Activity_
    extends Jgff_Dfflb_ff_Activity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.layout_jgff_dfflb_ff);
    }

    private void init_(Bundle savedInstanceState) {
        infoFile_ = new InfoFile_(this);
        dataHelper = DataHelper_.getInstance_(this);
    }

    private void afterSetContentView_() {
        tv_list_item_2 = ((TextView) findViewById(id.tv_list_item_2));
        tv_list_item_1 = ((TextView) findViewById(id.tv_list_item_1));
        view_2 = ((View) findViewById(id.view_2));
        second = ((RadioButton) findViewById(id.second));
        first = ((RadioButton) findViewById(id.first));
        rl_title = ((RelativeLayout) findViewById(id.rl_title));
        btn_upload = ((Button) findViewById(id.btn_upload));
        view_3 = ((View) findViewById(id.view_3));
        tv_list_item_6 = ((TextView) findViewById(id.tv_list_item_6));
        edt_search_1 = ((EditText) findViewById(id.edt_search_1));
        btn_chakan = ((Button) findViewById(id.btn_chakan));
        tv_list_item_5 = ((TextView) findViewById(id.tv_list_item_5));
        view_1 = ((View) findViewById(id.view_1));
        tvTitle_two_Name = ((TextView) findViewById(id.tvTitle_two_Name));
        view_6 = ((View) findViewById(id.view_6));
        tv_list_item_9 = ((TextView) findViewById(id.tv_list_item_9));
        view_5 = ((View) findViewById(id.view_5));
        tv_list_item_7 = ((TextView) findViewById(id.tv_list_item_7));
        rg = ((RadioGroup) findViewById(id.rg));
        tv_list_item_8 = ((TextView) findViewById(id.tv_list_item_8));
        btn_list_1 = ((Button) findViewById(id.btn_list_1));
        tv_list_item_4 = ((TextView) findViewById(id.tv_list_item_4));
        ll_4 = ((LinearLayout) findViewById(id.ll_4));
        ll_5 = ((LinearLayout) findViewById(id.ll_5));
        tv_list_item_3 = ((TextView) findViewById(id.tv_list_item_3));
        ll_2 = ((LinearLayout) findViewById(id.ll_2));
        ll_6 = ((LinearLayout) findViewById(id.ll_6));
        ll_1 = ((LinearLayout) findViewById(id.ll_1));
        btn_list_2 = ((Button) findViewById(id.btn_list_2));
        ll_3 = ((LinearLayout) findViewById(id.ll_3));
        view_4 = ((View) findViewById(id.view_4));
        edt_search_2 = ((EditText) findViewById(id.edt_search_2));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static Jgff_Dfflb_ff_Activity_.IntentBuilder_ intent(Context context) {
        return new Jgff_Dfflb_ff_Activity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Jgff_Dfflb_ff_Activity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Jgff_Dfflb_ff_Activity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
