//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.ZWPT.activity.R.id;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.DataHelper_;
import com.ZWPT.data.InfoFile_;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class Sjsl_Sjdj_shouli_Activity_
    extends Sjsl_Sjdj_shouli_Activity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.layout_sjdj_shouli);
    }

    private void init_(Bundle savedInstanceState) {
        infoFile_ = new InfoFile_(this);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        dataHelper = DataHelper_.getInstance_(this);
    }

    private void afterSetContentView_() {
        tv_sjdj_ffdd_second = ((TextView) findViewById(id.tv_sjdj_ffdd_second));
        edt_search_1 = ((EditText) findViewById(id.edt_search_1));
        tvTitle_two_Name = ((TextView) findViewById(id.tvTitle_two_Name));
        lv_sjdj_shouli_bltj = ((ListView) findViewById(id.lv_sjdj_shouli_bltj));
        ll_sjdj_csdd_first = ((LinearLayout) findViewById(id.ll_sjdj_csdd_first));
        btn_list_3 = ((Button) findViewById(id.btn_list_3));
        rl_title = ((RelativeLayout) findViewById(id.rl_title));
        ll_sjdj_tjcl_checkbox = ((LinearLayout) findViewById(id.ll_sjdj_tjcl_checkbox));
        tv_detail_jbxx_shoulididian = ((TextView) findViewById(id.tv_detail_jbxx_shoulididian));
        btn_list_1 = ((Button) findViewById(id.btn_list_1));
        btn_list_2 = ((Button) findViewById(id.btn_list_2));
        ll_sjdj_ffdd_first = ((LinearLayout) findViewById(id.ll_sjdj_ffdd_first));
        edt_search_2 = ((EditText) findViewById(id.edt_search_2));
        ll_detail_jbxx_shff = ((LinearLayout) findViewById(id.ll_detail_jbxx_shff));
        sjsl_lxfs = ((LinearLayout) findViewById(id.sjsl_lxfs));
        ll_sjdj_csdd_second = ((LinearLayout) findViewById(id.ll_sjdj_csdd_second));
        tv_sjdj_csdd_first = ((TextView) findViewById(id.tv_sjdj_csdd_first));
        tv_sjdj_ffdd_first = ((TextView) findViewById(id.tv_sjdj_ffdd_first));
        tv_sjdj_csdd_second = ((TextView) findViewById(id.tv_sjdj_csdd_second));
        btn_check_all = ((Button) findViewById(id.btn_check_all));
        edt_search_4 = ((EditText) findViewById(id.edt_search_4));
        edt_search_3 = ((EditText) findViewById(id.edt_search_3));
        btn_check_tiaojian = ((Button) findViewById(id.btn_check_tiaojian));
        ll_sjdj_tjcl_all = ((LinearLayout) findViewById(id.ll_sjdj_tjcl_all));
        lv_sjdj_shouli_tjcl = ((ListView) findViewById(id.lv_sjdj_shouli_tjcl));
        ll_sjdj_ffdd_second = ((LinearLayout) findViewById(id.ll_sjdj_ffdd_second));
        ((DataHelper_) dataHelper).afterSetContentView_();
        initView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static Sjsl_Sjdj_shouli_Activity_.IntentBuilder_ intent(Context context) {
        return new Sjsl_Sjdj_shouli_Activity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Sjsl_Sjdj_shouli_Activity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Sjsl_Sjdj_shouli_Activity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
