//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ZWPT.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.widget.ViewAnimator;
import com.ZWPT.activity.R.id;
import com.ZWPT.activity.R.layout;
import com.ZWPT.data.InfoFile_;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class Wdpz_User_Info_Activity_
    extends Wdpz_User_Info_Activity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.layout_wdpz_info);
    }

    private void init_(Bundle savedInstanceState) {
        infoFile_ = new InfoFile_(this);
    }

    private void afterSetContentView_() {
        ll_wdpz_xgmm = ((LinearLayout) findViewById(id.ll_wdpz_xgmm));
        edt_newpsd = ((EditText) findViewById(id.edt_newpsd));
        edt_danwei = ((EditText) findViewById(id.edt_danwei));
        edt_address = ((EditText) findViewById(id.edt_address));
        tv_wdpz_info_6 = ((TextView) findViewById(id.tv_wdpz_info_6));
        tv_wdpz_info_4 = ((TextView) findViewById(id.tv_wdpz_info_4));
        rl_title = ((RelativeLayout) findViewById(id.rl_title));
        btn_update_userInfo = ((Button) findViewById(id.btn_update_userInfo));
        edt_job = ((EditText) findViewById(id.edt_job));
        edt_arginpsd = ((EditText) findViewById(id.edt_arginpsd));
        btn_cancel_info = ((Button) findViewById(id.btn_cancel_info));
        tv_wdpz_info_10 = ((TextView) findViewById(id.tv_wdpz_info_10));
        edt_email = ((EditText) findViewById(id.edt_email));
        tv_wdpz_info_8 = ((TextView) findViewById(id.tv_wdpz_info_8));
        edt_fax_phone = ((EditText) findViewById(id.edt_fax_phone));
        edt_contanct_number = ((EditText) findViewById(id.edt_contanct_number));
        edt_usernumberinfo = ((EditText) findViewById(id.edt_usernumberinfo));
        edt_gongzuobumen = ((EditText) findViewById(id.edt_gongzuobumen));
        btn_cancel = ((Button) findViewById(id.btn_cancel));
        va_wdpz_info = ((ViewAnimator) findViewById(id.va_wdpz_info));
        btn_update_info = ((Button) findViewById(id.btn_update_info));
        tv_wdpz_info_9 = ((TextView) findViewById(id.tv_wdpz_info_9));
        tv_wdpz_info_3 = ((TextView) findViewById(id.tv_wdpz_info_3));
        tv_wdpz_info_7 = ((TextView) findViewById(id.tv_wdpz_info_7));
        tv_wdpz_info_2 = ((TextView) findViewById(id.tv_wdpz_info_2));
        edt_username = ((EditText) findViewById(id.edt_username));
        edt_oldpsd = ((EditText) findViewById(id.edt_oldpsd));
        edt_moblie_phone = ((EditText) findViewById(id.edt_moblie_phone));
        btn_update = ((Button) findViewById(id.btn_update));
        tv_wdpz_info_11 = ((TextView) findViewById(id.tv_wdpz_info_11));
        tv_wdpz_info_5 = ((TextView) findViewById(id.tv_wdpz_info_5));
        edt_IDnumber = ((EditText) findViewById(id.edt_IDnumber));
        tvTitle_two_Name = ((TextView) findViewById(id.tvTitle_two_Name));
        tv_wdpz_info_1 = ((TextView) findViewById(id.tv_wdpz_info_1));
        initView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static Wdpz_User_Info_Activity_.IntentBuilder_ intent(Context context) {
        return new Wdpz_User_Info_Activity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Wdpz_User_Info_Activity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Wdpz_User_Info_Activity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
